// Create web server with express
// Create a route for comments
// Create a route for comments/:id
// Create a route for comments/:id/edit
// Create a route for comments/:id/delete
// Create a route for comments/:id/update
// Create a route for comments/new
// Create a route for comments/create
// Create a route for comments/:id/like
